### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by deathmessinger** [lucasvienna/AdiBags_Dragonflight#3]
### Description

Whenever I open the options I get a chat msg saying missing local for every name and desc
![image](https://user-images.githubusercontent.com/11321799/233245323-e58de9fb-416d-4de2-875a-9d910754ee24.png)

### Addon Version

2.3.0

### World of Warcraft Flavor

Retail (Dragonflight)

### Tested with only AdiBags_Dragonflight

- [X] Yes
- [ ] No

### Lua Error

BugSack not showing anything

### Reproduction Steps

Open adibags options

**Comment by lucasvienna** [comment]
They are simply UI texts that I haven't added to the locale list properly yet :)

Are you perchance using the addon straight from GitHub? These messages only appear in the development build, so installing the release bundle would make these go away.

**Comment by deathmessinger** [comment]
Ah ok Thank you
